### ISSUE TITLE
Access token expired

### ISSUE THREAD

**Issue by 269693659** [lowcoding/lowcode-vscode#21]
使用截图初始化查询条件 出现Access token expired

**Comment by wjkang** [comment]
> 使用截图初始化查询条件 出现Access token expired

用的官方 api 还是第三方的？

**Comment by wjkang** [comment]
百度 OCR token 过期了，自己申请一个吧，免费的。改 share/BaiduOCR/request.ts 文件就行

**Comment by 269693659** [comment]
> 百度 OCR token 过期了，自己申请一个吧，免费的。改 share/BaiduOCR/request.ts 文件就行

好的，已解决
